create table MilkTea(
name varchar(100), category varchar(100),price integer,brand varchar(100)
);
create table Extra(
name varchar(100), category varchar(100),price integer,brand varchar(100)
);
/*Comebuy
碧螺春 原價40來店價35
四季春 原價40來店價35
錫蘭紅茶 原價30來店價25
茉莉綠茶 原價40來店價35
絕代雙Q奶茶 加15元升鮮奶
鮮奶凍奶茶 加15元升鮮奶
經典可可 加15元升鮮奶
暖薑奶茶 加15元升鮮奶
Coco
鮮奶茶系列 加20升大杯 加15加料升大杯
*/
insert into MilkTea(name,category,price,brand) values("茉莉綠茶", "醇香茶品",30,"Coco");
insert into MilkTea(name,category,price,brand) values("四季青春茶", "醇香茶品",30,"Coco");
insert into MilkTea(name,category,price,brand) values("莊園紅茶", "醇香茶品",30,"Coco");
insert into MilkTea(name,category,price,brand) values("四季珍椰青", "醇香茶品",40,"Coco");
insert into MilkTea(name,category,price,brand) values("雲朵奶蓋紅茶", "醇香茶品",45,"Coco");
insert into MilkTea(name,category,price,brand) values("雲朵奶蓋綠茶", "醇香茶品",45,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香凍紅茶", "醇香茶品",40,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香凍綠茶", "醇香茶品",40,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香凍青茶", "醇香茶品",40,"Coco");
insert into MilkTea(name,category,price,brand) values("綠豆沙", "冰沙系列",50,"Coco");
insert into MilkTea(name,category,price,brand) values("芒果冰沙", "冰沙系列",50,"Coco");
insert into MilkTea(name,category,price,brand) values("綠豆沙牛奶", "冰沙系列",65,"Coco");
insert into MilkTea(name,category,price,brand) values("綠豆沙自由配", "冰沙系列",60,"Coco");
insert into MilkTea(name,category,price,brand) values("百香綠茶", "果茶系列",35,"Coco");
insert into MilkTea(name,category,price,brand) values("鮮檸檬紅茶", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("鮮檸檬綠茶", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("鮮檸檬青茶", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("芒果綠茶", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("檸檬冬瓜露", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("蕎麥冬瓜露", "果茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香檸凍紅茶", "果茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香檸凍綠茶", "果茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香檸凍青茶", "果茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("蜜香檸凍冬茶", "果茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("百香雙響炮", "果茶系列",55,"Coco");
insert into MilkTea(name,category,price,brand) values("金桔檸檬", "果茶系列",50,"Coco");
insert into MilkTea(name,category,price,brand) values("冬瓜西谷米", "果茶系列",40,"Coco");
insert into MilkTea(name,category,price,brand) values("綠茶養樂多", "果茶系列",55,"Coco");
insert into MilkTea(name,category,price,brand) values("檸檬霸", "果茶系列",55,"Coco");
insert into MilkTea(name,category,price,brand) values("鮮榨蘋果百香", "果茶系列",55,"Coco");
insert into MilkTea(name,category,price,brand) values("鮮香橙冰茶", "果茶系列",60,"Coco");
insert into MilkTea(name,category,price,brand) values("星空葡萄", "果茶系列",75,"Coco");
insert into MilkTea(name,category,price,brand) values("阿薩姆奶茶", "奶茶系列",35,"Coco");
insert into MilkTea(name,category,price,brand) values("珍珠奶茶", "奶茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("西谷米奶茶", "奶茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("布丁奶茶", "奶茶系列",45,"Coco");
insert into MilkTea(name,category,price,brand) values("奶茶三兄弟", "奶茶系列",50,"Coco");
insert into MilkTea(name,category,price,brand) values("英式鮮奶茶(中杯)", "鮮奶茶系列",50,"Coco");
insert into MilkTea(name,category,price,brand) values("珍珠鮮奶茶", "鮮奶茶系列",65,"Coco");
insert into MilkTea(name,category,price,brand) values("芋頭鮮奶茶(中杯)", "鮮奶茶系列",60,"Coco");
insert into MilkTea(name,category,price,brand) values("黑糖珍珠鮮奶茶(中杯)", "鮮奶茶系列",50,"Coco");
insert into Extra(name,category,price,brand) values("珍珠", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("椰果", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("芋頭", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("仙草凍", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("布丁", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("西谷米", "加料",10,"Coco");
insert into Extra(name,category,price,brand) values("蜜香凍", "加料",10,"Coco");

insert into MilkTea(name,category,price,brand) values("烏龍綠茶", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("特級綠茶", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("錫蘭紅茶", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("極品菁茶", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("原鄉四季", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("特選普洱", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("翡翠烏龍", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("嚴選高山茶", "茗品系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("珍珠奶茶", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("錫蘭奶紅", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("烏龍奶茶", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("特級奶綠", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("仙草凍奶茶", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("椰果奶茶", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("布丁奶茶", "奶系列茶",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("暗黑水晶奶茶", "奶茶系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("粉圓奶茶", "奶茶系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜奶茶", "奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("芝麻奶茶", "奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("太妃鴛鴦奶茶", "奶茶系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("鮮奶茶", "鮮奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("鮮奶茶", "鮮奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("珍珠鮮奶茶", "鮮奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("鮮奶冬瓜", "鮮奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("粉圓鮮奶茶", "鮮奶茶系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("【清心隱藏版】珍珠蜂蜜鮮奶普洱", "鮮奶茶系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("頂級可可拿鐵", "拿鐵系列",70,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("咖啡拿鐵", "拿鐵系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("珍珠芝麻拿鐵", "拿鐵系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("濃情巧克力拿鐵", "拿鐵系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("優多綠茶", "優系列多",40,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("多多綠茶", "優多系列",40,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘆薈優多綠茶", "優多系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("優多檸檬", "優多系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("優多葡萄柚", "優多系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘋果醋", "果醋系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘋果醋紅茶", "果醋系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜蘋果醋", "果醋系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("藍莓醋", "果醋系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘆薈藍莓醋", "果醋系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜藍莓醋", "果醋系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘆薈蘋果醋", "果醋系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜蘋果醋紅茶", "果醋系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("藍莓醋紅茶", "果醋系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("優多藍莓醋紅茶", "果醋系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("冰淇淋紅茶", "冰淇淋系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("冰淇淋奶茶", "冰淇淋系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("【紅茶三兄弟】珍珠冰淇淋布丁紅茶", "冰淇淋系列",60,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("梅子綠茶", "特調系列",35,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜烏龍", "特調系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜綠茶", "特調系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("頂級可可", "特調系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("濃情巧克力", "特調系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜜茶", "特調系列",40,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("情人茶", "特調系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("咖啡奶茶", "特調系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("芋香奶茶", "特調系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("Red Bull紅牛無糖能量綠茶", "特調系列",75,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("Red Bull紅牛能量紅茶", "特調系列",75,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("冬瓜茶", "冬瓜系列",25,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("冬瓜菁茶", "冬瓜系列",35,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("冬瓜檸檬", "冬瓜系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("鳳梨紅茶", "季節限定",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("桂圓茶", "冬季節限定",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("桂圓鮮奶茶", "冬季節限定",70,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蜂蜜檸檬", "季節鮮果系列",55,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("蘆薈蜂蜜檸檬", "季節鮮果系列",65,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("金桔檸檬", "季節鮮果系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("葡萄柚綠茶", "季節鮮果系列",50,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("檸檬紅茶", "季節鮮果系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("檸檬綠茶", "季節鮮果系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("檸檬汁", "季節鮮果系列",45,"Ching-Shin Fu-Chuan");
insert into MilkTea(name,category,price,brand) values("葡萄柚汁", "季節鮮果系列",50,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("粉圓M", "加料",5,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("粉圓L", "加料",10,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("珍珠M", "加料",5,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("珍珠L", "加料",10,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("椰果", "加料",10,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("QQ", "加料",10,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("布丁", "加料",15,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("仙草凍", "加料",15,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("暗黑水晶", "加料",15,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("蘆葦", "加料",15,"Ching-Shin Fu-Chuan");
insert into Extra(name,category,price,brand) values("冰淇淋", "加料",15,"Ching-Shin Fu-Chuan");


insert into MilkTea(name,category,price,brand) values("碧螺春", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("四季春", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("鮮萃麥香紅茶", "原葉鮮萃茶",35,"Comebuy");
insert into MilkTea(name,category,price,brand) values("玫瑰普洱", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("烏龍綠茶(100%台灣茶)", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("茉莉烏龍(100%台灣茶)", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("斯里蘭卡烏瓦紅茶", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("海神", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("金萱茶", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("熟濸觀音(100%台灣茶)", "原葉鮮萃茶",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("文山包種(100%台灣茶)", "原葉鮮萃茶",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("東方美人(100%台灣茶)", "原葉鮮萃茶",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("白桃蜜烏龍", "原葉鮮萃茶",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("洛神蜜香紅茶", "原葉鮮萃茶",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("桂花四季春", "原葉鮮萃茶",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("柑橘大吉嶺", "原葉鮮萃茶",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("柑橘金萱", "原葉鮮萃茶",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("紅茶拿鐵", "鮮萃拿鐵茶",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("烏龍拿鐵(100%台灣茶)", "鮮萃拿鐵茶",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("四季春拿鐵", "鮮萃拿鐵茶",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("金萱拿鐵", "鮮萃拿鐵茶",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("觀音拿鐵(100%台灣茶)", "鮮萃拿鐵茶",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("錫蘭紅茶", "果茶系列",25,"Comebuy");
insert into MilkTea(name,category,price,brand) values("茉莉綠茶", "果茶系列",25,"Comebuy");
insert into MilkTea(name,category,price,brand) values("蜂蜜紅茶", "果茶系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("蜂蜜綠茶", "果茶系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("玉荷冰綠", "果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("檸檬冰茶", "果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("梅果茶", "果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("養樂多綠茶","果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("百香搖果樂", "果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("蘋果冰茶", "果茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("葡萄柚綠茶", "果茶系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("鳳梨冰茶", "果茶系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("芭C檸檬綠", "果茶系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("超桔霸氣飲", "果然系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("蜂蜜蘆薈", "果然系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("金桔檸檬", "果然系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("荔枝玉露", "果然系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("纖美小紫蘇", "果然系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("芭C檸檬多多", "果然系列",80,"Comebuy");
insert into MilkTea(name,category,price,brand) values("特調咖啡", "門市限定",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("招牌奶茶", "奶茶系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("黃金奶綠", "奶茶系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("珍珠奶茶", "奶茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("迷你珍珠奶茶", "奶茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("鮮萃麥香奶茶", "奶茶系列",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("海神奶茶", "奶茶系列",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("絕代雙Q奶茶", "奶茶系列",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("鮮奶凍奶茶", "奶茶系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("桂花奶綠", "奶茶系列",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("港式厚奶z(中杯)", "奶茶系列",65,"Comebuy");
insert into MilkTea(name,category,price,brand) values("觀音厚奶(中杯)", "奶茶系列",70,"Comebuy");
insert into MilkTea(name,category,price,brand) values("經典可可","奶茶系列",45,"Comebuy");
insert into MilkTea(name,category,price,brand) values("檸檬愛玉","夏季限定",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("百香果冰沙","夏季限定",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("七巧歐蕾","夏季限定",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("金芒果優乳","夏季限定",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("青檸香柚QQ","夏季限定",70,"Comebuy");
insert into MilkTea(name,category,price,brand) values("桂圓紅棗","冬季限定",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("暖薑茶","冬季限定",40,"Comebuy");
insert into MilkTea(name,category,price,brand) values("暖薑奶茶","冬季限定",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("熱檸茶","冬季限定",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("熱桔茶","冬季限定",50,"Comebuy");
insert into MilkTea(name,category,price,brand) values("黑糖薑汁可可","冬季限定",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("紫米可可","冬季限定",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("紫米奶茶","冬季限定",55,"Comebuy");
insert into MilkTea(name,category,price,brand) values("宇治抹茶","冬季限定",60,"Comebuy");
insert into MilkTea(name,category,price,brand) values("抹茶拿鐵","冬季限定",80,"Comebuy");
insert into Extra(name,category,price,brand) values("珍珠","加料",5,"Comebuy");
insert into Extra(name,category,price,brand) values("小紫蘇","加料",5,"Comebuy");
insert into Extra(name,category,price,brand) values("迷你珍珠(門市限定)","加料",5,"Comebuy");
insert into Extra(name,category,price,brand) values("門陣(門市限定)","加料",5,"Comebuy");
insert into Extra(name,category,price,brand) values("新雙Q(珍珠+芋圓+薯圓)","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("小芋圓(芋圓+薯圓)","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("搖果樂(珍珠+椰果+荔枝凍)","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("寒天晶球","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("椰果","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("愛玉","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("蘆薈","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("荔枝凍","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("紫米(冬季限定)","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("紅豆(冬季限定)","加料",10,"Comebuy");
insert into Extra(name,category,price,brand) values("仙草凍","加料",15,"Comebuy");
insert into Extra(name,category,price,brand) values("布丁","加料",15,"Comebuy");

select * from MilkTea;
select * from Extra;

